# GitHub Dependabot Configuration
# This will automatically create PRs to update dependencies

version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    # Limit the number of open PRs to avoid spam
    open-pull-requests-limit: 5
    # Group minor and patch updates together
    groups:
      development-dependencies:
        applies-to: version-updates
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        applies-to: version-updates
        dependency-type: "production"
        update-types:
          - "minor" 
          - "patch"
    # Auto-merge configuration
    reviewers:
      - "tavybrown"
    assignees:
      - "tavybrown"
    # Commit message preferences
    commit-message:
      prefix: "📦"
      prefix-development: "🛠️"
      include: "scope"
    # Custom labels for PRs
    labels:
      - "dependencies"
      - "automated"
    # Ignore specific packages if needed
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
      timezone: "America/New_York"
    open-pull-requests-limit: 3
    reviewers:
      - "tavybrown"
    assignees:
      - "tavybrown"
    commit-message:
      prefix: "🔧"
      include: "scope"
    labels:
      - "github-actions"
      - "dependencies"
      - "automated"

  # Enable version updates for Docker (if you use Docker)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "10:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 2
    reviewers:
      - "tavybrown"
    assignees:
      - "tavybrown"
    commit-message:
      prefix: "🐳"
      include: "scope"
    labels:
      - "docker"
      - "dependencies"
      - "automated"